<?php

use Illuminate\Support\Facades\Route;

/*
 * Collective Football API v1
 *
 * Every endpoint here follows:
 * - Controller → FormRequest → Service → Repository pattern
 * - Returns JsonResource (never raw arrays)
 * - Documented in docs/postman/collective-football.postman_collection.json
 * - OpenAPI spec auto-generated by Scramble
 *
 * When adding a new endpoint:
 * 1. Add route here
 * 2. Create FormRequest
 * 3. Create Controller method (thin — no logic)
 * 4. Create Service method (all logic here)
 * 5. Write unit test for Service
 * 6. Write feature test for Controller
 * 7. Add to Postman collection
 * 8. Run: php artisan scramble:export
 */

// Health (public)
Route::get('/health', fn () => response()->json([
    'status'  => 'ok',
    'version' => config('version.current'),
    'phase'   => config('version.phase'),
]))->name('api.v1.health');

// Auth
Route::prefix('auth')->group(function () {
    Route::post('/login', [\App\Http\Controllers\Api\V1\AuthController::class, 'login'])->name('api.v1.auth.login');
    Route::post('/logout', [\App\Http\Controllers\Api\V1\AuthController::class, 'logout'])->middleware('auth:sanctum')->name('api.v1.auth.logout');
});

// Authenticated routes
Route::middleware('auth:sanctum')->group(function () {

    // Manager profile
    Route::get('/user', [\App\Http\Controllers\Api\V1\ManagerController::class, 'show'])->name('api.v1.user');

    // Match engine
    Route::prefix('match')->group(function () {
        Route::post('/prepare', [\App\Http\Controllers\Api\V1\MatchController::class, 'prepare'])->name('api.v1.match.prepare');
        Route::post('/result', [\App\Http\Controllers\Api\V1\MatchController::class, 'result'])->name('api.v1.match.result');
        Route::get('/{match}', [\App\Http\Controllers\Api\V1\MatchController::class, 'show'])->name('api.v1.match.show');
    });

    // Players
    Route::apiResource('players', \App\Http\Controllers\Api\V1\PlayerController::class)->only(['index', 'show']);

    // Teams
    Route::apiResource('teams', \App\Http\Controllers\Api\V1\TeamController::class)->only(['index', 'show']);
});
